/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:58c5e3b4-18a2-4430-a1d3-dfd81431596b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9Ihkhf8zT",
    "aws_user_pools_web_client_id": "444a8h40s1okk9uqrlhr9c0j14",
    "oauth": {}
};


export default awsmobile;
